#!/bin/sh

THIS_DIR=$(dirname $0)
PROJECT_ROOT_DIR=$THIS_DIR/../..

# Copy Dockerfile from this folder to project root folder
cp $PROJECT_ROOT_DIR/docker/api_dev/Dockerfile $PROJECT_ROOT_DIR/

# Bring up development environment
cd $THIS_DIR
FIG_FILE=fig_dev.yml fig $@
