poppy:
    build: ../api/.
    ports:
     - "81:8081"
    environment:
     DNS_USERNAME: CloudUsername
     DNS_APIKEY: CloudApiKey
     DNS_URL: DNSUrlToUse
     DNS_EMAIL: YourEmailAddress

     FASTLY_APIKEY: FastlyApiKey

     AKAM_POLICY_API_CLIENT_TOKEN: value
     AKAM_POLICY_API_CLIENT_SECRET: value
     AKAM_POLICY_API_ACCESS_TOKEN: value
     AKAM_POLICY_API_BASE_URL: value
     AKAM_CCU_API_CLIENT_TOKEN: value
     AKAM_CCU_API_CLIENT_SECRET: value
     AKAM_CCU_API_ACCESS_TOKEN: value
     AKAM_CCU_API_BASE_URL: value
     AKAM_ACCESS_URL_LINK: value
    links:
     - cassandra
     - zookeeper

zookeeper:
    image: jplock/zookeeper
    ports:
     - "2181:2181"

cassandra:
    build: ../cassandra/.
    ports:
     - "9160:9160"
     - "9042:9042"