repose:
  build: ../repose/.
  ports:
   - "80:8080"
  environment:
   KEYSTONE_ADMIN: Username
   KEYSTONE_PASSWORD: Password
   KEYSTONE_URI: Uri
   DESTINATION_HOST: poppy
   DESTINATION_PORT: 8081
  links:
   - poppy
poppy:
    build: ../api/.
    ports:
     - "81:8081"
    environment:
     DNS_USERNAME: CloudUsername
     DNS_APIKEY: CloudApiKey
     DNS_URL: DNSUrlToUse
     DNS_EMAIL: YourEmailAddress

     FASTLY_APIKEY: FastlyApiKey

     AKAM_POLICY_API_CLIENT_TOKEN: 
     AKAM_POLICY_API_CLIENT_SECRET: 
     AKAM_POLICY_API_ACCESS_TOKEN: 
     AKAM_POLICY_API_BASE_URL: 
     AKAM_CCU_API_CLIENT_TOKEN: 
     AKAM_CCU_API_CLIENT_SECRET: 
     AKAM_CCU_API_ACCESS_TOKEN: 
     AKAM_CCU_API_BASE_URL: 
     AKAM_ACCESS_URL_LINK: 
    links:
     - cassandra


cassandra:
    build: ../cassandra/.
    ports:
     - "9160:9160"
     - "9042:9042"