cassandra:
    build: ../cassandra/.
    ports:
     - "9160:9160"
     - "9042:9042"

zookeeper:
    image: jplock/zookeeper
    ports:
     - "2181:2181"

mimic:
    build: ../mimic/.
    ports:
     - "8900:8900"
