zookeeper:
    image: jplock/zookeeper
    ports:
     - 2181:2181

cassandra:
    image: library/cassandra
    ports:
     - 9160:9160
     - 9042:9042

mimic:
    image: amitgandhinz/mimic
    ports:
     - 8900:8900