poppy:
    build: ../api/.
    ports:
     - "80:8080"
    links:
     - cassandra
     - zookeeper

zookeeper:
    extends:
        file: development.yml
        service: zookeeper

cassandra:
    extends:
        file: development.yml
        service: cassandra